[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
citef = "main:app"

[project]
name = 'citation-forecast'
description = 'Forecast academic impact (citation count/percentile) with NLP'

version = '1.2.0'
requires-python = '>=3.13'

readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]

dependencies = [
    'polars==1.38.1',
    'pandas==2.3.3',
    'mlflow==3.9.0',
    'torch==2.10.0',
    'transformers==5.0.0',
    'scikit-learn==1.8.0',
    'typer==0.23.1',
    'seaborn==0.13.2',
]

[project.optional-dependencies]
modal = ["modal>=0.73.0"]

authors = [
    { name = 'Felix Noble', email = 'felix.noble@live.co.uk' }
]
