experiment = "transformer_class"

[env]
tracking_uri = "http://127.0.0.1:5000"
raw_loc      = "/home/fnoble/Data/OpenAlex-parquet/"
staged_loc   = "/home/fnoble/Data/"
artifact_loc = "/home/fnoble/experiment-tracking/artifacts"

[runtime]
default = "local"

[runtime.modal]
project = "citef"
raw_volume = "openalex-raw"
staged_volume = "openalex-staged"
gpu = "T4"
embedder_batch_size = 64
